name: Backend Build

on:
  push:
    branches:
      - main
      - backend
    paths:
      - "backend/**"

  pull_request:
    branches:
      - main
      - backend
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install

      - name: Type Check
        run: bun run typecheck

      - name: Build
        run: bun run build
